name: Gradle Build Project

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        gradle-version: 7.4.2
    - name: Extract version
      id: version_ext
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: 'gradle.properties'
        properties: 'kmt.version'
    - name: Check release
      run: echo ${{ steps.version_ext.outputs.kmt-version }}
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        tag_name: ${{ steps.version_ext.outputs.kmt-version }}
        release_name: ${{ steps.version_ext.outputs.kmt-version }}
        body_path: ./RELEASE.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/libs/KMT-${{ steps.version_ext.outputs.kmt-version }}.jar
        asset_name: KMT-${{ steps.version_ext.outputs.kmt-version }}.jar
        asset_content_type: application/java-archive
    - name: Publish to GithubPackages
      run: gradle wrapper --gradle-version 7.4.2 publish
      env:
        GITHUB_USER: PolyRocketMatt
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


