name: Dokka

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dokka:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build and run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        gradle-version: 7.4.2
    - name: Generate Dokka documentation
      run: gradle wrapper --gradle-version 7.4.2 dokkaHtmlMultiModule
    - name: Deploy API documentation to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dokka
        CLEAN: true
